name:          Code Guide by Food52
description:   Standards for developing flexible, durable, and sustainable HTML, CSS and SCSS.
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
